### ISSUE TITLE
`in area` lint

### ISSUE THREAD

**Issue by Mothblocks** [OpenDreamProject/OpenDream#1003]
Would be cool to lint over this for tg:

```dm
for (var/obj/thing in my_cool_area)
```

...as this performs a hidden `in world` loop.

For OpenDream this might not be relevant since I would hope it Does Not Do That but would be nice

**Comment by ike709** [comment]
EZ pragma

**Comment by LemonInTheDark** [comment]
it's worth noting that this is NOT ALWAYS SUB-OPTIMAL in dm.
At least not without tracking thing in area manually. There's a call in shuttle movement that gets slower with it "optimized" (I think?), etc.

It seems to scale somewhat with how large the area actually is? Not totally sure, never got a good handle on it

**Comment by ike709** [comment]
@LemonInTheDark Don't worry that's why we can just use pragmas to tweak the emission :^)

**Comment by wixoaGit** [comment]
From #1544:
> I don't see a reason for us to have a warning that doesn't apply to OD. This seems like a better fit for something like DreamChecker whose target is BYOND.
