### ISSUE TITLE
Incorrect processing order of const object vars

### ISSUE THREAD

**Issue by ZeWaka** [OpenDreamProject/OpenDream#1011]
It seems constant vars in objects aren't getting processed in the right order.  Perhaps related to #803

Test Case:
```
/datum/foo
  var/other_var = MY_CONSTANT
  var/const/MY_CONSTANT = 1
```

BYOND: Compilation Successful, behaves as expected

OpenDream: `Unknown identifier "MY_CONSTANT"`

**Comment by Insineer** [comment]
There is the problem not only in the const vars processing order relative to ordinary vars, but with the only const vars processing order too

Example below is compiled successfuly by BYOND, but OpenDream returns error:
```
var/const/access_maint_tunnels2 = access_maint_tunnels
var/const/access_maint_tunnels = 12
```

```
Error OD0000 at code.dm:138:55: Unknown identifier "access_maint_tunnels"
```
