### ISSUE TITLE
Put `Trident/7.0;` in our browser's user-agent

### ISSUE THREAD

**Issue by wixoaGit** [OpenDreamProject/OpenDream#1023]
TGUI, which is in many modern codebases, looks for the regex `Trident\/(\d+).+?;` in the browser's user-agent and refuses to work properly if it's not there. We should add it to ours to get it working.

From what I can tell this will require a change to RobustToolbox's WebView.

**Comment by wixoaGit** [comment]
We'll likely end up copying a version of IE's user-agent entirely. Here's the one I get in BYOND:
`Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
`

**Comment by ike709** [comment]
`WCvars.UserAgentOverride` now exists but we're blocked by https://github.com/space-wizards/RobustToolbox/issues/3703

**Comment by ike709** [comment]
The blocker is fixed in the latest version of RT, we just need to update.

**Comment by ZeWaka** [comment]
RT is now updated
