### ISSUE TITLE
Relative var definitions unsupported

### ISSUE THREAD

**Issue by amylizzle** [OpenDreamProject/OpenDream#1030]
```
var/const
    STATE_LOGGEDOFF = 1
    STATE_LOGGEDIN = 2
```
Should result in two constants, instead causes unknown identifier error at compile.

**Comment by ike709** [comment]
I'm assuming this is in a type declaration and not in a proc?

**Comment by amylizzle** [comment]
yes

**Comment by wixoaGit** [comment]
I can't replicate this. I suspect it was actually a definition order bug which has been fixed for a while.
