### ISSUE TITLE
Label causes identifier to be unknown

### ISSUE THREAD

**Issue by amylizzle** [OpenDreamProject/OpenDream#1032]
```
selection:
var/IP = input(output_target, "Select item to view fingerprints, cancel to close window.", "[src]'s inventory") as null|anything in OL

if (!IP || !output_target || !ismob(output_target))
	return
```

Triggers unknown identifier error for `IP`

**Comment by ike709** [comment]
I wonder if the label is putting the next statement the compiler finds (the `IP` var decl.) and putting it inside the label scope then immediately exiting said scope. We had a similar issue with `for` loops in the past.

Maybe BYOND just doesn't make a label scope if the next statement isn't indented?
