### ISSUE TITLE
Indentation before #include causes undefined var error

### ISSUE THREAD

**Issue by Insineer** [OpenDreamProject/OpenDream#1050]
## Description

OpenDream fails to parse first object definition in the file, when file's include line begins with indentation.

## Steps to reproduce

Add folowing line starting with indentation to TestGame .dme file:

```
    #include "exodus_announcements.dm"
```

Example "exodus_announcements.dm" file content:

```
/obj/TestObj
	a = "The Emergency Shuttle has docked with the station. You have approximately %ETD% to board the Emergency Shuttle."
```

OpenDream compiles with error:

```
Error OD0405 at exodus_announcements.dm:2:4: Cannot override undefined var "a"
```

At the same time, BYOND compiles it without any issues.

## Initial research

I've taken a look to this problem in the debugger and found that problem is in DMLexer. DMObjectBuilder tries to process `/obj/TestObj/a` override statement, and encounters wrong statement's ObjectPath:

![image](https://user-images.githubusercontent.com/22466026/215367415-1f735dda-4a32-4766-b8b0-17cda4c6ced8.png)

ObjectPath should be `/obj/TestObj` instead of `/datum/map` which is simply previous processed block's ObjectPath.

## Workaround

Removing indentation before #include file's line solves the problem.

**Comment by ike709** [comment]
The indentation before the `#include` persists after the preprocessor inserts the included DM file's contents, so the first line of the included file has the same indentation.

The example becomes:
```
	/obj/TestObj
	a = "The Emergency Shuttle has docked with the station. You have approximately %ETD% to board the Emergency Shuttle."
```
