### ISSUE TITLE
`__TYPE__` needs to be implemented

### ISSUE THREAD

**Issue by ZeWaka** [OpenDreamProject/OpenDream#1074]
> `__TYPE__` compiles as the current type path, or as null within a global proc.

**Comment by ike709** [comment]
> or as null within a global proc.

I don't think we currently replicate this?

**Comment by ZeWaka** [comment]
what does it return currently 😅

**Comment by ZeWaka** [comment]
![image](https://user-images.githubusercontent.com/4741640/223919009-addf92c1-82b9-440d-a673-3f94fa8cb03e.png)
