### ISSUE TITLE
`jointext()` doesn't cope with non-lists correctly

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#1086]
https://www.byond.com/docs/ref/#/proc/jointext

Right now OD `jointext()` doesn't have BYOND parity. For example, if `List` is a string, it should return `List`.

Someone needs to test calling it with all the various types as args and seeing what happens, then replicate parity in OD (and add a unit test).

**Comment by out-of-phaze** [comment]
Fixed by #1113.
