### ISSUE TITLE
switch case dosnt work with non static variables

### ISSUE THREAD

**Issue by HaCsO** [OpenDreamProject/OpenDream#1095]
Error cause when we have switch case with non static variables
```
proc/do_somethin(var/arg_one, var/obj/thing)
    var/limit = 100
    switch(thing.sometype)
        if(1 to arg_one)
            ...
        if(arg_one to limit)
           ...
```

**Comment by ike709** [comment]
BYOND doesn't allow non-static variables in switches. A bug caused it to not raise a compiler error, which was fixed in 515.1600.

https://www.byond.com/forum/post/2750423
