### ISSUE TITLE
JavaScript executes before the DOM finishes loading

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#1130]
JavaScript executes and sets window.location before the dom finishes loading, cutting the document short and breaking TGUI on TG.

**Comment by wixoaGit** [comment]
This is just a consequence of using CEF and would be unreasonable to fix. TGUI itself was changed to accommodate this in https://github.com/tgstation/tgstation/pull/79244 and will hopefully become a non-issue over time.
