### ISSUE TITLE
Assign being treated as named argument

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#1225]
TG contains this code: `if(isnull((smoothing_groups = GLOB.bitflag_lists[txt_signature])))`

It causes the following runtime: `[ERRO] world.log: Exception occurred: /proc/isnull has no argument named smoothing_groups`

According to wixoa, the compiler is treating that as if the parentheses aren't there and it's a named argument.

**Comment by ike709** [comment]
Small test case:
```
/proc/foo()
	var/list/test_list_one= null
	var/list/test_list_two= list("bar")
	if(isnull((test_list_one= test_list_two[1])))
		world.log << "was null"
	else
		world.log << "wasnt null"
```
Call `foo()` and you'll see the runtime happen.

**Comment by martinlyra** [comment]
Decided to taken on this myself. My investigation has shown that the `Expression` does call `ExpressionPrimary()` with the `allowparenthesis` still set to `true`. So the parenthesis are consumed once the expression has been parsed, making it harder to discern whether the assignment was wrapped or not.

**Comment by martinlyra** [comment]
I was able to fix this, PR pending. However I did discover that the current implementation does not support parenthesis wrapping of expressions where you should be able to do in BYOND. See #1276
