### ISSUE TITLE
TG exceeds the turf appearance ID limit

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#1227]
![image](https://github.com/OpenDreamProject/OpenDream/assets/5714543/335cddb7-e7a4-4401-b08a-b2f5cba35919)

Right above the error message logging is this TODO:
`// TODO: Maybe separate appearance IDs and turf IDs to prevent this possibility`

Looks like that TODO needs to get done.

**Comment by wixoaGit** [comment]
Fixed by #1435
