### ISSUE TITLE
Named arguments like `dir` to `image()` no longer work properly

### ISSUE THREAD

**Issue by out-of-phaze** [OpenDreamProject/OpenDream#1261]
Passing `dir = foo` etc. into the `image()` proc or `new image` constructor no longer sets the corresponding variable. Caused by #1203.

Details:
`var/image/I = image('icons/turf/flooring/shadows.dmi', cstr, AO_LAYER, BITFLAG(i-1))` works, dir is set and not inherited.
`var/image/I = image('icons/turf/flooring/shadows.dmi', cstr, dir = BITFLAG(i-1))` does not work, unclear if dir is set because it's inherited.
The stack that's pushed is:
`null, PushResource 'icons/turf/flooring/shadows.dmi', null, PushString cstr, null, PushString "dir"` in the broken case
`PushResource 'icons/turf/flooring/shadows.dmi', PushString cstr, PushFloat AO_LAYER, PushString "dir"` in the working case
The image constructor code expects to find `dir` at index 3 because there's no `loc`, but in the keyed case it's placed at index 4 because `image/New()` is defined as `New(icon, loc, icon_state, layer, dir, pixel_x, pixel_y)`: `dir` is at index 5.

How do we fix this? Uh, no clue.

**Comment by out-of-phaze** [comment]
![image](https://cdn.discordapp.com/attachments/847318834952405045/1111036174442692689/image.png)
Visual example of the effects of the issue. `dir` is being passed as `pixel_x` instead.

**Comment by LemonInTheDark** [comment]
you guys use that hidden image flag to decide if an overlay inherits dir or not right?

**Comment by wixoaGit** [comment]
> you guys use that hidden image flag to decide if an overlay inherits dir or not right?

Yes, we have that
