### ISSUE TITLE
`savefile << object` is not implemented

### ISSUE THREAD

**Issue by martinlyra** [OpenDreamProject/OpenDream#1306]
https://www.byond.com/docs/ref/#/savefile/operator/%3c%3c

The file of interest is https://github.com/OpenDreamProject/OpenDream/blob/1b80c46ef2ffcabcd4e6cea0cffe52ac65fbc0b1/OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs#L8-L9

Which would need this implemented:
https://github.com/OpenDreamProject/OpenDream/blob/1b80c46ef2ffcabcd4e6cea0cffe52ac65fbc0b1/OpenDreamRuntime/Objects/DreamObject.cs#L383-L387

**Comment by amylizzle** [comment]
Should be close, already handled in https://github.com/OpenDreamProject/OpenDream/blob/81a2a0470e07c90687f1dc1c81ea78b01a29d218/OpenDreamRuntime/Procs/DMOpcodeHandlers.cs#L2057-L2062
