### ISSUE TITLE
`/world/Topic()` is not supported

### ISSUE THREAD

**Issue by wixoaGit** [OpenDreamProject/OpenDream#1341]
https://www.byond.com/docs/ref/#/world/proc/Topic

~Looks like it's an HTTP GET request handler on the server~ It's a custom TCP protocol!

As used by the BYOND.TopicSender library [here](https://github.com/Cyberboss/BYOND.TopicSender/blob/d9e273943c2f9cc91b205d0050b1190ee475de75/Byond.TopicSender/TopicClient.cs#L113)

**Comment by ike709** [comment]
Reopened since #1382 was reverted by #1398

**Comment by Cyberboss** [comment]
Should be fixed soon or OD isn't gonna be in the initial release of TGS 6

**Comment by Cyberboss** [comment]
And by soon, I mean by about a month from now
