### ISSUE TITLE
skin elements with an empty name throw runtimes

### ISSUE THREAD

**Issue by ZeWaka** [OpenDreamProject/OpenDream#1344]
`System.ArgumentException: An item with the same key has already been added. Key:`

`at OpenDreamClient.Interface.InterfaceMenu.AddChild(ElementDescriptor descriptor) in OpenDreamClient\Interface\InterfaceMenu.cs:line 49`
Example elements that get flagged as duplicates:
```
elem
	name = ""
	command = ""
	category = "&Audio"
```
These end up rendering as spacers/horizontal rules, which is why they're used for Goon.
![image](https://github.com/OpenDreamProject/OpenDream/assets/4741640/a0cef96a-4081-4e3e-9c23-be0d4c5be087)

**Comment by amylizzle** [comment]
Fixed by #1402
