### ISSUE TITLE
Compile error, illicit conversion of TransformComponent to boolean in DMISpriteComponent

### ISSUE THREAD

**Issue by FluffyGhoster** [OpenDreamProject/OpenDream#1351]
During compilation of OpenDream, we get the following error in our CI:

`/home/runner/OpenDream/OpenDreamClient/Rendering/DMISpriteComponent.cs(60,58): error CS1503: Argument 2: cannot convert from 'Robust.Shared.GameObjects.TransformComponent' to 'bool' `

**Comment by wixoaGit** [comment]
Is your RobustToolbox submodule on the right commit? It should be on the tag `v130.0.0`

**Comment by FluffyGhoster** [comment]
> Is your RobustToolbox submodule on the right commit? It should be on the tag `v130.0.0`

I am not sure how to verify this, the code is acquired via the following commands:

```
git clone https://github.com/OpenDreamProject/OpenDream.git $HOME/OpenDream
git -C $HOME/OpenDream submodule update --init --recursive
```

And then built with:

```
dotnet restore $HOME/OpenDream
dotnet build $HOME/OpenDream/OpenDream.sln -c Release --property WarningLevel=1
```

The build was successful until ~14 hours ago, at which point successive runs started failing

**Comment by wixoaGit** [comment]
Hmm, that's odd. I don't see anything wrong with those commands, but this looks like a mismatch in RT version and we haven't touched RT in over a week.

**Comment by wixoaGit** [comment]
Looking at the CI's logs here, it's pulling the latest RT commit
https://github.com/Aurorastation/Aurora.3/actions/runs/5435047260/jobs/9883873755?pr=16607

**Comment by wixoaGit** [comment]
I think it's the use of `--remote` [here](https://github.com/Aurorastation/Aurora.3/blob/master/tools/ci/install_od.sh#L11)  which sets the submodule to the latest commit.

**Comment by FluffyGhoster** [comment]
It might have something to do with the new cache usage, I think due to this other command that runs when the cache is successfully restored:

`git -C $HOME/OpenDream submodule update --remote`
Possibly because it uses the HEAD pointer implicitly, with the --remote option, for what I understand

**Comment by FluffyGhoster** [comment]
Yep, that was it, thank you very much wixoa!
