### ISSUE TITLE
Error message on failing to load map is very unclear

### ISSUE THREAD

**Issue by amylizzle** [OpenDreamProject/OpenDream#1352]
If a map isn't included in the compiled json for whatever reason, the runtime crashes with a null ref error.

obviously temporary code that hasn't been fixed: 
```
_dreamMapManager.InitializeAtoms(_compiledJson.Maps![0]);
```

**Comment by wixoaGit** [comment]
This should already be handled by [this](https://github.com/OpenDreamProject/OpenDream/blob/master/OpenDreamRuntime/DreamManager.cs#L107)
