### ISSUE TITLE
Client reconnection should fully reload state like BYOND

### ISSUE THREAD

**Issue by Cyberboss** [OpenDreamProject/OpenDream#1520]
The server dying and instantly coming back does not reset the client.

There should be a restart protocol if the server detects a new client connected to an old session.

**Comment by ike709** [comment]
This is more to do with our shoddy connection state handling than any issue with RT or TGS.

**Comment by wixoaGit** [comment]
I have not been able to replicate this. The client disconnects and moves to the main menu a few moments after the server closes, which is expected behavior.

**Comment by Cyberboss** [comment]
Right, well I'm going to move the goalpost if you don't mind. For TGS updates to work, clients need to be able to seamlessly reconnect and restart.
