### ISSUE TITLE
Feature Request: OpenDream Hub Implementation

### ISSUE THREAD

**Issue by Hinaichigo** [OpenDreamProject/OpenDream#1551]
It would be cool if there was support for 'hub servers' analogous to the BYOND Hub so people could find servers more easily. Especially once OD starts being used more, it would make it easier for smaller servers to migrate to OD because people could find those servers more easily.

**Comment by wixoaGit** [comment]
Since we are built on top of RobustToolbox we already have support for the same hub/launcher SS14 uses.
