### ISSUE TITLE
When respawned, the dead HUD element appears

### ISSUE THREAD

**Issue by mudzbe** [OpenDreamProject/OpenDream#1585]
![image](https://github.com/OpenDreamProject/OpenDream/assets/60084963/907ffb81-279c-44f7-b8d0-a3945a55528b)

I got respawned by admins after gibbed spontaneously but the dead HUD element appeared on my character
Examine shows you are alive, all controls work

On SS14 paradise test

**Comment by ike709** [comment]
Presumably fixed by https://github.com/OpenDreamProject/OpenDream/pull/1565 fixing `client.images`

**Comment by ike709** [comment]
Can't reproduce; presumably fixed by #1565
