### ISSUE TITLE
Entity drifting through walls

### ISSUE THREAD

**Issue by mudzbe** [OpenDreamProject/OpenDream#1587]
For a few seconds an engie borg was drifting diagonally bearing 315, I didn't get a screenshot before it disappeared

Round ID 4 paradise SS14 test

**Comment by wixoaGit** [comment]
Likely a bug with gliding

**Comment by ike709** [comment]
![image](https://github.com/user-attachments/assets/cc03a0dc-b807-4d75-9091-94a0b04cd1c6)


Should be fixed by changes to gliding.
