### ISSUE TITLE
`roll()` is always returning 1

### ISSUE THREAD

**Issue by optimumtact** [OpenDreamProject/OpenDream#1604]
To reproduce, go to the bar and find the dice on the table.

Roll the d20 or the d6 and see they land on 1

![image](https://github.com/OpenDreamProject/OpenDream/assets/2544323/013df93c-64ca-4a24-bcb5-721a3a0a28ec)

I am not sure if this is intentional or the RNG is broken.

**Comment by wixoaGit** [comment]
The way the `roll()` proc is being used by the dice ends up always returning 1.
