### ISSUE TITLE
Subtract blending is inverted

### ISSUE THREAD

**Issue by itsmeow** [OpenDreamProject/OpenDream#1617]
BYOND does src - dst, not dst - src.

https://github.com/OpenDreamProject/OpenDream/blame/a3dcd596ff1db5cc06299fe1eee8ce3ebd679fd5/OpenDreamRuntime/Objects/DreamIcon.cs#L317

**Comment by wixoaGit** [comment]
In that code `dst` represents the icon being blended onto, and `src` is where the color is coming from.

`icon1.Blend(icon2, ICON_SUBTRACT)`
`icon2` would be `src` here and `icon1` is `dst`. My testing in BYOND is showing that it does `icon1 - icon2` which makes the current code correct.

**Comment by itsmeow** [comment]
Oh? My interpretation was backwards then. Apologies. When I ported this logic to Rust I assumed src was the icon being blended onto.
