### ISSUE TITLE
Nebula: dots in paths break on Linux

### ISSUE THREAD

**Issue by out-of-phaze** [OpenDreamProject/OpenDream#1754]
Check the CI fail here: https://github.com/NebulaSS13/Nebula/actions/runs/8713893798/job/23903138848?pr=3899
```dm
	return "<IMG src='\ref['./icons/chattags.dmi']' class='text_tag' iconstate='[tagname]'" + (tagdesc ? " alt='[tagdesc]'" : "") + ">"
```
`Error OD0404 at code/_helpers/text.dm:417:48: Cannot find file './icons/chattags.dmi'`
OD seems to be breaking on `./` in the path there. That doesn't happen locally on my Windows machine, only on the Linux release in CI.

**Comment by ike709** [comment]
Added context:
![image](https://github.com/OpenDreamProject/OpenDream/assets/5714543/c9cbc578-3652-4528-9437-d3225f3fecdc)
