### ISSUE TITLE
Lint for pointless/bad positional arguments.

### ISSUE THREAD

**Issue by moonheart08** [OpenDreamProject/OpenDream#1768]
In cases like https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/69ce25bd79b41b7800e33c45ccb9a094a280c5ff/code/modules/gamemaster/actions/atmos_leak.dm#L20-L23
```dm
...
severity = pickweight(EVENT_LEVEL_MUNDANE = 8,
EVENT_LEVEL_MODERATE = 5,
EVENT_LEVEL_MAJOR = 3
)
...
// Event defines.
#define EVENT_LEVEL_MUNDANE        1
#define EVENT_LEVEL_MODERATE    2
#define EVENT_LEVEL_MAJOR        3
...
```

After preprocessing, this is
```dm
// This runtimes if the argument order is different.
severity = pickweight(1 = 8,
2 = 5,
3 = 3
)
```
which is equivalent to
```dm
severity = pickweight(8, 5, 3)
```
this is almost certainly unintentional, undoubtably does not do what the programmer intended (a BYOND classic frankly), and should probably be linted for.

**Comment by ike709** [comment]
Added context I haven't verified for myself:
![image](https://github.com/OpenDreamProject/OpenDream/assets/5714543/b4b32443-8462-4967-932d-8a664cd0437b)
