### ISSUE TITLE
`initial(foo.type)` gives `null`

### ISSUE THREAD

**Issue by Kapu1178** [OpenDreamProject/OpenDream#1786]
```
/obj
  name = "Hello"

/proc/main()
  var/obj/foo = /obj
  ASSERT(foo.type == /obj)
  ASSERT(initial(foo.type) == /obj)
  ASSERT(foo.name == "Hello")
```
This works in BYOND.

**Comment by wixoaGit** [comment]
The problematic expression here is `foo.type` (which is a shortcut for `initial(foo.type)` in this case). While we support this shortcut, doing `initial(foo.type)` doesn't work since `type` is a specially handled var that doesn't really have an initial value. This causes it to give `null`.
