### ISSUE TITLE
OD does not recognize the "hidden" verb setting

### ISSUE THREAD

**Issue by Kapu1178** [OpenDreamProject/OpenDream#1787]
Title. It will runtime upon attempting to read it.

**Comment by wixoaGit** [comment]
Relevant code [here](https://github.com/OpenDreamProject/OpenDream/blob/a769dd772ca1540a3a266c63fdfb4bdc698a41c7/OpenDreamRuntime/DreamThread.cs#L75). It is missing a case for `"hidden"`.
