### ISSUE TITLE
Goon: everyone is naked

### ISSUE THREAD

**Issue by amylizzle** [OpenDreamProject/OpenDream#1818]
On goonstation master (https://github.com/goonstation/goonstation/commit/d73bbdebf58fb12b45cecd0dbf3f5699188c889a as of this issue) every human is rendering as if naked. In-hand sprites work, but equipped things do not render.

**Comment by ike709** [comment]
Fixed by https://github.com/OpenDreamProject/OpenDream/pull/1816
