### ISSUE TITLE
Opendream fails to parse expression

### ISSUE THREAD

**Issue by Cyprex** [OpenDreamProject/OpenDream#1958]
Opendream chokes on the following: https://github.com/Rotwood-Vale/Ratwood-Keep/blob/main/code/modules/antagonists/roguetown/villain/aspirant.dm#L37-L41 
With these errors: 
```
Error OD0001 at code/modules/antagonists/roguetown/villain/aspirant.dm:40:87: Expected ')' 
Error OD0001 at code/modules/antagonists/roguetown/villain/aspirant.dm:40:87: Expected end of proc statement
Error OD0001 at code/modules/antagonists/roguetown/villain/aspirant.dm:41:11: Expected end of proc statement
Warning OD0000 at code/modules/antagonists/roguetown/villain/aspirant.dm:43:3: Error recovery had to skip to code/modules/antagonists/roguetown/villain/aspirant.dm:43:8
```

Oddly enough the first error does *not* appear in the VSCode problems tab, making this extra confusing. Also note that:
```
if(!new_owner.assigned_role in GLOB.noble_positions || !new_owner.assigned_role in GLOB.garrison_positions) //broken
if(!(new_owner.assigned_role in GLOB.noble_positions || !new_owner.assigned_role) in GLOB.garrison_positions) //works
if(!(new_owner.assigned_role in GLOB.noble_positions) || !(new_owner.assigned_role in GLOB.garrison_positions))//works
```

**Comment by wixoaGit** [comment]
OD is parsing the expression as `(!new_owner.assigned_role) in (GLOB.noble_positions || !new_owner.assigned_role)` and stopping there because `in` is not greedy. This leaves the parser at the second `in` token, rather than the `)` it expects to end the `if`.

> Oddly enough the first error does _not_ appear in the VSCode problems tab

This is probably related to both errors being on the same token/position in the file.

**Comment by wixoaGit** [comment]
Running this in BYOND
```
var/list/a = list("a")
var/list/b = list("b")
var/list/c = list("b", 1)

world.log << ("a" in a || "b")
world.log << ("a" in a || "b" in b)
world.log << ("a" in a || "b" in c)
```
Produces
```
1
0
1
```
Which indicates that `"a" in a || "b" in b` is parsed as `("a" in (a || "b")) in b`

**Comment by Cyprex** [comment]
That's fucking awful. Does that not violate what the DM reference says about operator precedence?

**Comment by wixoaGit** [comment]
> That's fucking awful. Does that not violate what the DM reference says about operator precedence?

Nope. According to https://www.byond.com/docs/ref/#/operator `in` is the last step in any expression. The ref also points out some similar common mistakes https://www.byond.com/docs/ref/#/operator/in
