### ISSUE TITLE
`atom/override` not implemented

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#201]
http://www.byond.com/docs/ref/#/atom/var/override

**Comment by amylizzle** [comment]
Partially fixed by #1362 but only for client images. Need to add the behaviour to overlays as well.

**Comment by wixoaGit** [comment]
> Partially fixed by #1362 but only for client images. Need to add the behaviour to overlays as well.

What do you mean by adding the behavior to overlays? The reference says this var only applies to images.

**Comment by amylizzle** [comment]
oh I thought images added to `.overlays` with `override = 1` on them would override too, but they don't. Think this can be closed then!
