### ISSUE TITLE
Savefile operators don't work anymore

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#604]
wixoa nuking `IDreamProcIdentifier` made `savefile["entry"] << 1 and savefile["entry"] >> var`  non-functional, which is blocking https://github.com/wixoaGit/OpenDream/issues/559

**Comment by ike709** [comment]
Also the fix is to make `a << b` a statement with a different instruction from the bitshift expression.

See https://discord.com/channels/847318834952405042/847318834952405045/944707503038529636

**Comment by wixoaGit** [comment]
Fixed by #894
