### ISSUE TITLE
Using `.` in `for()` throws exceptions

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#656]
Code:
```
/obj/item/reagent_containers/food/snacks/customizable/Destroy()
	for(. in ingredients)
		qdel(.)
	return ..()
```
`Error at code\modules\food_and_drinks\food\customizables.dm:145:7: Expected ')'`

**Comment by wixoaGit** [comment]
This is no longer an issue.

Funny thing to note, this loop leaves `.` null after it finishes.
