### ISSUE TITLE
Object definition var declaration not considered constant when it should be

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#693]
**Case 1:**
`var/static/list/all_drawables = graffiti + symbols + drawings + oriented + runes + graffiti_large_h`

The declared var and all of the vars that comprise it are static lists on `/obj/item/toy/crayon`.

`Add` calls `TryAsConstant()` on LHS & RHS and eventually it gets to `GlobalField.TryAsConstant()` which is false because they're not considered const.

**Case 2:**
A datum definition declares `var/static/list/list_symptoms = subtypesof(/datum/symptom)` which the preproc evaluates as `var/static/list/list_symptoms = typesof(/datum/symptom) - /datum/symptom`

This fails because `ProcCall` the way we currently handle it is not considered constant.

Both need to be resolved for TG.

**Comment by Hinaichigo** [comment]
What seems like a related issue is:
```
154	switch(amount)
155		if(0)
156			icon_state = "linenbin-empty"
157		if(1 to amount / 2)
158			icon_state = "linenbin-half"
159		else				icon_state = "linenbin-full"
```
generates an error:
`Error at code\game\objects\structures\bedsheet_bin.dm:157:19: Expected a constant`

**Comment by Hinaichigo** [comment]
This is what causes the `Invalid initial value` error right?

**Comment by wixoaGit** [comment]
Yes
