### ISSUE TITLE
Operator overloading is unimplemented

### ISSUE THREAD

**Issue by Hinaichigo** [OpenDreamProject/OpenDream#732]
When attempting to compile /vg/station, the following error occurs:
`Error at code\__HELPERS\math\vector\vector.dm:73:24: Expected end of object statement`
the relevant lines:
```
73	/vector/proc/operator+(var/vector/B)
74		return new /vector(x + B.x, y + B.y)
```
It seems that operator overloading isn't implemented.

**Comment by amylizzle** [comment]
Fixed by  #1196, though they now throw unimplemented warnings instead as they can be defined but will never be called.

**Comment by wixoaGit** [comment]
I would still consider that unimplemented

**Comment by Hinaichigo** [comment]
@amylizzle What was the main reason that #944 couldn't be merged?

**Comment by amylizzle** [comment]
Mostly because the way procs worked was refactored and I didn't want to fix the merge, but also the general approach I'd taken didn't allow for some of the operators to actually work, notably the index operators.

**Comment by Hinaichigo** [comment]
Thanks for explaining.

**Comment by ike709** [comment]
Closing in favor of https://github.com/OpenDreamProject/OpenDream/issues/1854 which is tracking the status of each operator overload.
