### ISSUE TITLE
Error setting vars on world

### ISSUE THREAD

**Issue by Hinaichigo** [OpenDreamProject/OpenDream#804]
When compiling /vg/station, the following two errors occur:
```
Error at code\world.dm:10:17: Cannot override undefined var cache_lifespan
Error at code\world.dm:14:16: Cannot override undefined var movement_mode
```
at:
```
6	/world
7		mob = /mob/new_player
8		turf = /turf/space
9		view = "15x15"
10		cache_lifespan = 0	//stops player uploaded stuff from being kept in the rsc past the current session
11		//loop_checks = 0
12		icon_size = WORLD_ICON_SIZE
13		sleep_offline = FALSE
14		movement_mode = PIXEL_MOVEMENT_MODE
```
This error only started occurring somewhat recently. This might be related to #735.

**Comment by Altoids1** [comment]
This is because these vars aren't actually defined in DMStandard I don't think, and now that override logic is working, it's picking up the problem. (Previous code used to just spontaneously transmute these into their own var definitions).

**Comment by Hinaichigo** [comment]
So it's the same thing as being unimplemented?

**Comment by Altoids1** [comment]
Mhm, this error will be fixed by #774.

**Comment by Hinaichigo** [comment]
This still produces a compilation error for `movement_mode`

**Comment by ike709** [comment]
...Yes, because the fix PR isn't merged yet.
