### ISSUE TITLE
Floats behave slightly funny on OD

### ISSUE THREAD

**Issue by redmoogle** [OpenDreamProject/OpenDream#843]
Byond seems to not have rounding issues unlike OD
<br>
test code
```dm
var/a = 0
for(var/i in 1 to 21)
    world.log << a
    a += 0.05
```
<br>

```dm
var/a = 0
for(var/i in 1 to 10001)
    a += 0.0001
for(var/i in 1 to 10001)
    a -= 0.0001
world.log << a * 1000000000
```
Results in -50.3933 on byond & -50.393284 on OD
So it seems like the string conversion truncates the floating point numbers

<br>

OD
![image](https://user-images.githubusercontent.com/20369082/194872598-56443e85-3c5a-4dca-93f8-d30017428657.png)

Byond
![image](https://user-images.githubusercontent.com/20369082/194872238-cd68e5f4-cb8f-463a-9461-733c400e754d.png)

**Comment by Altoids1** [comment]
AFAIK the issue is specifically in how we display floats. BYOND (thank goodness) actually does do correct IEEE arithmetic for these floats, they are just displayed in a truncated way sometimes.

**Comment by redmoogle** [comment]
Yes the back end their the same but visually its not done right

afaik the algo for it is if its less than 0.0001 round to 4 decimals otherwise IEEE
