### ISSUE TITLE
Weird NaN Comparison behavior

### ISSUE THREAD

**Issue by redmoogle** [OpenDreamProject/OpenDream#879]
`ASSERT(1.#IND == 1.#IND)` will return true on byond and false on opendream (what the fuck?)

but doing `ASSERT(trunc(1.#IND) == 1.#IND)` both return false

**Comment by Altoids1** [comment]
I think in the real IEEE spec, NaN is not supposed to be equal to itself. This is BYOND contradicting the floating-point standard, I think.

**Comment by ike709** [comment]
The *actual* NaN value does not equal itself in BYOND, this issue seems to be specific to `1.#IND`

**Comment by redmoogle** [comment]
515 seemingly fixed this
