### ISSUE TITLE
Tracking Issue for DM versioning specification

### ISSUE THREAD

**Issue by ZeWaka** [OpenDreamProject/OpenDream#883]
This is a tracking issue for determining exactly and keeping track of features that depend on the open dream compiler & runtime having some way to support different versions of the stdlib at once. Example: supporting DM versions 514 and 515.

This could be done several ways: a flag you pass to the compiler, some configuration, `#if DM_VERSION > 1590` and such. Implementation ideally should be discussed by several members of the project before moving forward with it.

**Comment by wixoaGit** [comment]
We are just targeting v515 now.
