### ISSUE TITLE
`pick()` parity bug

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#903]
In BYOND if you pass an empty list it'll runtime with a `pick() from empty list` error. OD doesn't replicate this behavior from what I can tell (I'm at work right now so I can't investigate super thoroughly).

**Comment by PowerfulBacon** [comment]
It doesn't runtime if you do pick(null) however

**Comment by wixoaGit** [comment]
I think it would error in OD because [this](https://github.com/OpenDreamProject/OpenDream/blob/45d41d6dbcb0b0e1e4a6c67ba710cdf7fb565106/OpenDreamRuntime/Procs/DMOpcodeHandlers.cs#L1837) would end up doing `values[0]` on an empty list. A more friendly exception would be welcome though.

**Comment by Insineer** [comment]
> I think it would error in OD because [this](https://github.com/OpenDreamProject/OpenDream/blob/45d41d6dbcb0b0e1e4a6c67ba710cdf7fb565106/OpenDreamRuntime/Procs/DMOpcodeHandlers.cs#L1837) would end up doing `values[0]` on an empty list. A more friendly exception would be welcome though.

Yeah, that's right. It actually threw an exception, so I just added one with more clear error text.
