### ISSUE TITLE
`>>=` and `<<=` operators are broken

### ISSUE THREAD

**Issue by willox** [OpenDreamProject/OpenDream#922]
`>>=` and `<<=` are broken 

https://github.com/OpenDreamProject/OpenDream/blob/15de2c2c7621a032946073a672c4a7e462ec096a/DMCompiler/DM/Expressions/Binary.cs#L607-L610

https://github.com/OpenDreamProject/OpenDream/blob/15de2c2c7621a032946073a672c4a7e462ec096a/DMCompiler/DM/Expressions/Binary.cs#L594-L597

invalid use of references, no test case because i am playing Tom Clancy's Rainbow Six® Siege

**Comment by Altoids1** [comment]
I despise Tom Clancy's Rainbow Six® Siege™️
