### ISSUE TITLE
Utilize .NET 7 ASCII Helpers

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#931]
![image](https://user-images.githubusercontent.com/5714543/203177467-ef740c13-31b8-40c1-bf9e-51aa3048c713.png)

.NET 7 adds these and there's certainly places where we could likely benefit from using them.

This issue exists mainly to stop us from forgetting about it.

**Comment by wixoaGit** [comment]
Most notably [these four methods](https://github.com/OpenDreamProject/OpenDream/blob/8c740751310733642491328f098a24ada08b1b21/OpenDreamShared/Compiler/Lexer.cs#L117) which I have seen show up as hotspots in profiling
