### ISSUE TITLE
Lateral proc overrides do not behave correctly in OD

### ISSUE THREAD

**Issue by Altoids1** [OpenDreamProject/OpenDream#933]
OD currently doesn't really differentiate between (and understand the parsing of) proc overrides and proc definitions. Instead, it emits compile-times like these:
```
Error at code\modules\antagonists\changeling\powers\transform.dm:167:7: Type /datum/antagonist/changeling already has a proc named "select_dna"
```
Whenever code like this is discovered:
```dm
/datum/antagonist/changeling/select_dna(var/prompt, var/title)
// ... and then later on in the file ...
/datum/antagonist/changeling/proc/select_dna(var/prompt, var/title)
```

**Comment by Hinaichigo** [comment]
Just wondering, what's the functional purpose and intended behavior of something like the example you gave above?

**Comment by Altoids1** [comment]
> Just wondering, what's the functional purpose and intended behavior of something like the example you gave above?

This is just part of DM's ability to be read out-of-order. Overriding procs on the same type, in general, is used by codebases like Yogs (as a measure to reduce git conflicts when merging in from /TG/)

**Comment by Hinaichigo** [comment]
I see thanks!
