### ISSUE TITLE
Use union for DreamValue

### ISSUE THREAD

**Issue by PJB3005** [OpenDreamProject/OpenDream#99]
Using a union would allow you to avoid all boxing operations with `DreamValue`. Layout would look something like this:

```cs
[StructLayout(LayoutKind.Explicit)]
struct DreamValue
{
    [Flags]
    public enum DreamValueType : byte {
        String = 1,
        Integer = 2,
        Float = 4,
        Number = Integer | Float,
        DreamResource = 8,
        DreamObject = 16,
        DreamPath = 32,
        DreamProc = 64
    }

    [FieldOffset(0)]
    public DreamValueType Type { get; private set; }
    [FieldOffset(4)]
    public float FloatValue { get; private set; }
    [FieldOffset(4)]
    public int IntValue { get; private set; }
    [FieldOffset(8)] 
    public object RefValue { get; private set; }

    public DreamValue(String value)
    {
        Unsafe.SkipInit(out this);
        RefValue = value;
        IntValue = default;
        Type = DreamValueType.String;
    }

    public DreamValue(int value)
    {
        Unsafe.SkipInit(out this);
        RefValue = default;
        IntValue = value;
        Type = DreamValueType.Integer;
    }

    public DreamValue(int value)
    {
        Unsafe.SkipInit(out this);
        RefValue = default;
        FloatValue = value;
        Type = DreamValueType.Float;
    }

    public DreamValue(UInt32 value) : this((int) value)
    {
    }
}
```

It does beg the question though: why do you allow storing an int in `DreamValue`? It's not a real data type in DM and it sounds like it would only complicate the code. This wouldn't be necessary if `DreamValue` stores only floats.

**Comment by ike709** [comment]
@ZeWaka since you were looking into boxing memes

**Comment by ZeWaka** [comment]
@PJB3005 Your conversion doesn't account for `DreamValue.Null` - however, do you think we could use `0` for it?

**Comment by PJB3005** [comment]
Just set all the fields to 0 in that case, yes.

**Comment by ike709** [comment]
@wixoaGit Thoughts?

**Comment by wixoaGit** [comment]
> It does beg the question though: why do you allow storing an int in DreamValue? It's not a real data type in DM and it sounds like it would only complicate the code.

You're right, DreamValue doesn't need to store integers, and its ability to do this should be removed.

> This wouldn't be necessary if DreamValue stores only floats.

What do you mean by this? Wouldn't we still want to have a union with `FloatValue` and `RefValue` fields?

**Comment by PJB3005** [comment]
> What do you mean by this? Wouldn't we still want to have a union with FloatValue and RefValue fields?

Because of limitations with the GC, you can't overlap ref and non-ref fields like that, sadly.

Also you wouldn't save any space anyways unless you want to get into complex NaN-boxing type stuff because you'd still have the type field.

**Comment by wixoaGit** [comment]
The idea of making DreamValue into a union is no longer relevant since these are now the only two fields on it, and boxing is not as much of a concern anymore.
```cs
private object? _refValue;
private readonly float _floatValue;
```
